# frozen_string_literal: true

module Spree
  class Promotion < Spree::Base
    module Actions
      class FreeShipping < Spree::PromotionAction
        def perform(payload = {})
          order = payload[:order]
          promotion_code = payload[:promotion_code]

          custom_shipping_methods = order.shipments.select{|s| s.shipping_method.name != 'Standard Shipping'}
          standard_shipping = order.shipments.select{|s| s.shipping_method.name == 'Standard Shipping'}

          shipments = custom_shipping_methods + standard_shipping
          created_adjustments = shipments.map do |shipment|
            remove_from(order) unless standard_shipping_method(shipment)
            next if promotion_credit_exists?(shipment)
            next unless standard_shipping_method(shipment)

            shipment.adjustments.create!(
              order: shipment.order,
              amount: compute_amount(shipment),
              source: self,
              promotion_code: promotion_code,
              label: label
            )
          end

          # Did we actually end up creating any adjustments?
          # If so, then this action should be classed as 'successful'
          created_adjustments.any?
        end

        def label
          "#{I18n.t('spree.promotion')} (#{promotion.name})"
        end

        def compute_amount(shipment)
          shipment.cost * -1
        end

        # Removes any adjustments generated by this action from the order's
        #  shipments.
        # @param order [Spree::Order] the order to remove the action from.
        # @return [void]
        def remove_from(order)
          order.shipments.each do |shipment|
            shipment.adjustments.each do |adjustment|
              if adjustment.source == self
                shipment.adjustments.destroy(adjustment)
              end
            end
          end
        end

        private

        def promotion_credit_exists?(shipment)
          shipment.adjustments.where(source: self).exists?
        end

        def standard_shipping_method(shipment)
          shipment&.shipping_method&.name == "Standard Shipping"
        end
      end
    end
  end
end

# touched on 2025-05-22T19:17:58.119505Z
# touched on 2025-05-22T20:34:16.354549Z
# touched on 2025-05-22T22:31:23.193390Z
# touched on 2025-05-22T23:21:39.617964Z
# touched on 2025-05-22T23:42:23.603957Z
# touched on 2025-05-22T23:46:25.073619Z
# touched on 2025-05-22T23:46:31.323989Z