:concurrency: 5
:max_retries: 5

:queues:
  - [algoliasearch, 4]
  - [default, 2]
  - [netsuite, 1]
  - [productcard, 1]

:schedule:
  hello:
    class: HelloWorld
  abandoned_cart_email:
    every: "1.day"
    at: "7:00"
    class: AbandonedCartDailyTask
  empty_abandoned_orders:
    every: "1.day"
    at: "8:00"
    class: EmptyAbandonedOrdersTask
  bulk_update_facebook_data:
    every: "1.day"
    at: "6:00"
    class: BulkUpdateFacebookData
  sitemap_update:
    every: "1.day"
    at: "6:00"
    class: SitemapWorker
  stockout_email:
    cron: "0 7 * * MON"
    class: StockoutReport

# touched on 2025-05-22T21:33:39.215145Z
# touched on 2025-05-22T22:55:07.793243Z